apiVersion: apps/v1
kind: Deployment
metadata:
  name:  techtrends
  labels:
    app:  techtrends
  namespace: prodtechtrends
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techtrends
  template:
    metadata:
      labels:
        app:  techtrends
    spec:
      containers:
      - image:  mynamerahulkumar/techtrends:latest
        name:   techtrendpro
        resources:
          requests:
            cpu: "250m"
            memory: "64Mi"
          limits:
            cpu: "500m"
            memory: "128Mi" 
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3111
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3111
        ports:
        - containerPort:  3111